"""initial_schema

Revision ID: 507ccfe2225d
Revises: 
Create Date: 2026-05-09 10:47:30.340343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507ccfe2225d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('rover_id', sa.String(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('triggered_replan', sa.Boolean(), nullable=False),
    sa.Column('replan_mission_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomalies_mission_id'), ['mission_id'], unique=False)

    op.create_table('environments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('grid', sa.JSON(), nullable=False),
    sa.Column('temperature_k', sa.Float(), nullable=False),
    sa.Column('pressure_pa', sa.Float(), nullable=False),
    sa.Column('active_geysers', sa.JSON(), nullable=False),
    sa.Column('hazard_zones', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('environment_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('rover_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('rover_id', sa.String(), nullable=False),
    sa.Column('planner', sa.String(), nullable=False),
    sa.Column('waypoints', sa.JSON(), nullable=False),
    sa.Column('estimated_total_battery', sa.Float(), nullable=False),
    sa.Column('estimated_steps', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_mission_id'), ['mission_id'], unique=False)

    op.create_table('rovers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('battery', sa.Float(), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('path_history', sa.JSON(), nullable=False),
    sa.Column('samples_collected', sa.Integer(), nullable=False),
    sa.Column('steps_taken', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('anomalies_encountered', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rovers_mission_id'), ['mission_id'], unique=False)

    op.create_table('telemetry_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('rover_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('battery_pct', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_events_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_events_rover_id'), ['rover_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('objectives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('target_x', sa.Integer(), nullable=False),
    sa.Column('target_y', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('command', sa.JSON(), nullable=False),
    sa.Column('estimated_battery_cost', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_steps')
    op.drop_table('objectives')
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_telemetry_events_rover_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_events_mission_id'))

    op.drop_table('telemetry_events')
    with op.batch_alter_table('rovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rovers_mission_id'))

    op.drop_table('rovers')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_mission_id'))

    op.drop_table('plans')
    op.drop_table('missions')
    op.drop_table('environments')
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomalies_mission_id'))

    op.drop_table('anomalies')
    # ### end Alembic commands ###
