"""add_rover_fps_and_aegis_fields

Revision ID: aaf21fbd308b
Revises: 507ccfe2225d
Create Date: 2026-05-19 17:34:47.636161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf21fbd308b'
down_revision: Union[str, Sequence[str], None] = '507ccfe2225d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rovers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anomaly_streak', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('safe_mode_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('autonomy_level', sa.String(), nullable=False, server_default='supervised'))
        batch_op.add_column(sa.Column('aegis_objectives_generated', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rovers', schema=None) as batch_op:
        batch_op.drop_column('aegis_objectives_generated')
        batch_op.drop_column('autonomy_level')
        batch_op.drop_column('safe_mode_reason')
        batch_op.drop_column('anomaly_streak')

    # ### end Alembic commands ###
